CREATE TABLE spirit
(
    spirit_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    apv          NUMERIC(5, 2),
    age_in_month INT,
    price        NUMERIC(10, 2)
);
